Repository ios-study-boost/Hazzle-iOS, pull requests merged in 2020-11, with the labels that each got.

#26 [#4] 습관 추가 화면
  Hazzle/Hazzle/HabitCreate/HabitCreateViewController.swift
Labels: UI

#29 [#11] feat: 메인페이지 UI 구현
  Hazzle/Hazzle.xcodeproj/project.pbxproj
  Hazzle/Hazzle/Home/HomeViewController.swift
  Hazzle/Podfile.lock
Labels: UI, feature

#31 [#30] 습관, 메모 객체
  Hazzle/Hazzle/Model/Habit.swift
  Hazzle/Hazzle/Model/Memo.swift
Labels: feature

#32 feat: 습관 추가 화면 기능 구현
  Hazzle/Hazzle/HabitCreate/HabitCreateViewController.swift
  Hazzle/Hazzle/Info.plist
  Hazzle/Hazzle/Supporting Files/Assets.xcassets/acorn.imageset/Contents.json
  Hazzle/Hazzle/Supporting Files/Assets.xcassets/acorn.imageset/acorn-1.png
  Hazzle/Hazzle/Supporting Files/Assets.xcassets/acorn.imageset/acorn-2.png
  Hazzle/Hazzle/Supporting Files/Assets.xcassets/acorn.imageset/acorn.png
  Hazzle/Podfile.lock
Labels: feature

#33 [#12] feat : 완료 갤러리 UI
  Hazzle/Hazzle.xcodeproj/project.pbxproj
  Hazzle/Hazzle/Finished/Finished.storyboard
  Hazzle/Hazzle/Finished/FinishedViewController.swift
  Hazzle/Hazzle/Finished/cell/FinishedCollectionViewCell.swift
  Hazzle/Hazzle/Finished/cell/FinishedCollectionViewCell.xib
  Hazzle/Hazzle/Home/HomeViewController.swift
Labels: UI, feature
