Repository ios-study-boost/Hazzle-iOS, pull requests merged in 2020-10, with the labels that each got.

#5 feat: 데이터베이스 객체 생성
  Hazzle/Hazzle.xcodeproj/project.pbxproj
  Hazzle/Hazzle/Model/Alarm.swift
  Hazzle/Hazzle/Model/Habit.swift
  Hazzle/Hazzle/Model/Memo.swift
Labels: feature

#7 feat: 데이터베이스 모델 객체 생성
  .github/PULL_REQUEST_TEMPLATE.md
  Hazzle/Hazzle.xcodeproj/project.pbxproj
  Hazzle/Hazzle/Model/Alarm.swift
  Hazzle/Hazzle/Model/Habit.swift
  Hazzle/Hazzle/Model/Memo.swift
Labels: feature

#17 feat: 기능별 그룹 생성
  Hazzle/Hazzle.xcodeproj/project.pbxproj
  Hazzle/Hazzle.xcworkspace/xcshareddata/IDEWorkspaceChecks.plist
  Hazzle/Hazzle/Finished/Finished.storyboard
  Hazzle/Hazzle/Finished/FinishedViewController.swift
  Hazzle/Hazzle/HabitCreate/HabitCreate.storyboard
  Hazzle/Hazzle/HabitCreate/HabitCreateViewController.swift
  Hazzle/Hazzle/HabitDetail/HabitDetail.storyboard
  Hazzle/Hazzle/HabitDetail/HabitDetailViewController.swift
  Hazzle/Hazzle/Home/Home.storyboard
  Hazzle/Hazzle/Home/HomeViewController.swift
  Hazzle/Hazzle/Statistics/Statistics.storyboard
  Hazzle/Hazzle/Statistics/StatisticsViewController.swift
  Hazzle/Hazzle/Supporting Files/AppDelegate.swift
  Hazzle/Hazzle/Supporting Files/Assets.xcassets/AccentColor.colorset/Contents.json
  Hazzle/Hazzle/Supporting Files/Assets.xcassets/AppIcon.appiconset/Contents.json
  Hazzle/Hazzle/Supporting Files/Assets.xcassets/Contents.json
  Hazzle/Hazzle/Supporting Files/Base.lproj/LaunchScreen.storyboard
  Hazzle/Hazzle/Supporting Files/SceneDelegate.swift
Labels: feature

#19 [#16] feat: 스토리보드 연결
  Hazzle/Hazzle/Base.lproj/Main.storyboard
  Hazzle/Hazzle/Finished/Finished.storyboard
  Hazzle/Hazzle/HabitCreate/HabitCreate.storyboard
  Hazzle/Hazzle/HabitDetail/HabitDetail.storyboard
  Hazzle/Hazzle/Home/Home.storyboard
  Hazzle/Hazzle/Statistics/Statistics.storyboard
  Hazzle/Hazzle/Supporting Files/SceneDelegate.swift
Labels: feature

#20 feat: Home, Finished 네비게이션 컨트롤러 생성
  Hazzle/Hazzle/Base.lproj/Main.storyboard
  Hazzle/Hazzle/Finished/Finished.storyboard
  Hazzle/Hazzle/Home/Home.storyboard
Labels: feature

#21 style: 모델 객체 타입 명시
  Hazzle/Hazzle/Model/Alarm.swift
  Hazzle/Hazzle/Model/Habit.swift
  Hazzle/Hazzle/Model/Memo.swift
Labels: style

#22 [#18] feat: 상세 페이지 UI
  Hazzle/Hazzle/HabitDetail/HabitDetailViewController.swift
  Hazzle/Hazzle/Supporting Files/Assets.xcassets/testImage.imageset/Contents.json
  Hazzle/Hazzle/Supporting Files/Assets.xcassets/testImage.imageset/IMG_2714.jpeg
Labels: UI, feature
